baseurl = "https://bonvic.dev"
languageCode = "en-us"
title = "Bonvic Bundi"
theme = "bon"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"
pluralizeListTitles = false
enableGitInfo = true

[permalinks]
posts = "blog/:slug/"

[params]
about = "Software engineer. Mostly doing backend work with Python."
meta = "Bonvic's blog. | Software engineer. Mostly doing fullstack work with Typescript and Golang."
author = "Bonvic Bundi"
authorTitle = "Software Engineer"
numberOfPostsInHomePage = 3
lastUpdated = "September 19th, 2024"

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 1

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 2

[[menus.main]]
name = 'Reading'
pageRef = '/reading'
weight = 3

[[menus.main]]
name = 'Watching'
pageRef = '/watching'
weight = 4

[[menus.socials]]
name = "Github"
url = "https://github.com/b0nbon1"
weight = 1

[[menus.socials]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/bonvic-bundi/"
weight = 2

[[menus.socials]]
name = "Email"
url = "mailto:bundi.bonvic@gmail.com"
weight = 3

[[menus.footer]]
name = 'Github'
url = "https://github.com/b0nbon1"
weight = 1

[[menus.footer]]
name = 'LinkedIn'
url = "https://www.linkedin.com/in/bonvic-bundi/"
weight = 2

[[menus.footer]]
name = 'Email'
url = "mailto:bundi.bonvic@gmail.com"
weight = 3

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"

[markup]
[markup.highlight]
style = "borland"
[markup.goldmark.renderer]
unsafe = true
